CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(120) NOT NULL,
    email         VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE provider_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    category     VARCHAR(60) NOT NULL,
    bio          VARCHAR(1000),
    rating_avg   DOUBLE PRECISION NOT NULL DEFAULT 0,
    rating_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_provider_category ON provider_profiles(category);

CREATE TABLE service_offerings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id      BIGINT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
    name             VARCHAR(120) NOT NULL,
    description      VARCHAR(500),
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes >= 5),
    price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    active           BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE availability_rules (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES provider_profiles(id) ON DELETE CASCADE,
    day_of_week VARCHAR(12) NOT NULL,
    start_time  TIME NOT NULL,
    end_time    TIME NOT NULL,
    CHECK (end_time > start_time)
);
CREATE INDEX idx_rules_provider_day ON availability_rules(provider_id, day_of_week);

CREATE TABLE bookings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id   BIGINT NOT NULL REFERENCES provider_profiles(id),
    service_id    BIGINT NOT NULL REFERENCES service_offerings(id),
    customer_id   BIGINT NOT NULL REFERENCES users(id),
    start_time    TIMESTAMP NOT NULL,
    end_time      TIMESTAMP NOT NULL,
    status        VARCHAR(20) NOT NULL,
    notes         VARCHAR(500),
    reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
    version       BIGINT NOT NULL DEFAULT 0,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    CHECK (end_time > start_time)
);
CREATE INDEX idx_bookings_provider_time ON bookings(provider_id, start_time);
CREATE INDEX idx_bookings_customer ON bookings(customer_id);

-- Last line of defence against double booking: even if application logic is bypassed,
-- the database refuses two ACTIVE bookings that start at the same instant for one provider.
CREATE UNIQUE INDEX uq_booking_active_slot
    ON bookings(provider_id, start_time)
    WHERE status IN ('PENDING', 'CONFIRMED');

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    provider_id BIGINT NOT NULL REFERENCES provider_profiles(id),
    customer_id BIGINT NOT NULL REFERENCES users(id),
    rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     VARCHAR(1000),
    created_at  TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_reviews_provider ON reviews(provider_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(100) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL
);
